apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tool-state-ingress
spec:
  rules:
    - host: tool-state.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tool-state
                port:
                  number: 80
